### ISSUE TITLE
DC Jurisdiction image is missing

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#101]
<img width="1231" alt="Screen Shot 2022-10-21 at 8 35 46 AM" src="https://user-images.githubusercontent.com/7707627/197208894-1a7583a3-a7a2-4f20-98c3-b783e55aeb82.png">

**Comment by cfhull** [comment]
@james-minton It looks like we're just completely missing this file. Might need to reach out to Noelle to get this done.
