### ISSUE TITLE
Hexbin

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#105]
- [ ] Tooltips
- [ ] OnClick routing to individual pages
- [ ] Fix size of Bureau of Prisons hexagon

**Comment by james-minton** [comment]
- [ ] Add drop-shadow and correct sizing of letters for state abbreviations within each hexbin -- important for accessibility because the white letters can get lost in the lighter-colored hexbins

**Comment by james-minton** [comment]
Closing as this has been consolidated into #41
