### ISSUE TITLE
Homepage: scrollytelling with static background

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seeing-solitary#119]
I'd like to try a different animation style in a couple of places; implementing it once could provide enough of a template to do in the other instances.

For the "How many people are held for a year or more" section I'd like to have a yellow background that gets "locked" to the viewport while elements get animated in with scroll. So the overall viewport remains static while the user scrolls, but the text and graphics change, until the animation is done. Here are the animation steps:

**Step 1**

![state1](https://user-images.githubusercontent.com/33635008/197830460-a220899f-dbf5-4220-bd23-dec7eb03a2e6.jpg)

**Step 2**

![state2](https://user-images.githubusercontent.com/33635008/197830496-044510ab-2210-44b0-a572-5dea995e46eb.jpg)

**Step 3** 

![state3](https://user-images.githubusercontent.com/33635008/197830585-f69f0157-2ef2-45bb-b7af-404d1b00ab64.jpg)

We could use 3 different SVGs for the graphic.

I'm looking around for instances of this style -- best I can find is on [this page of a site we built](https://dallasisd.resourceexplorer.org/), because it locks the background to the viewport while other elements change. Also, it uses Framer Motion (see [relevant folder in the repo](https://github.com/Hyperobjekt/cpal-site/tree/master/src/components/AnimatedScroll)). One difference is that I don't want the text to "scroll by" like in this example; I want it to fade into its designated place per the steps shown above.

![Hhr5xqjh2g](https://user-images.githubusercontent.com/33635008/197831557-dc48d3f5-4b8d-484e-ac7f-b99c66e1fd58.gif)

**Comment by cfhull** [comment]
I have this working, but the first 2 SVGs should have one less person on the outside
