### ISSUE TITLE
Where numeric figure has no data, in place of "??" it should read "Not provided" in a smaller font.

### ISSUE THREAD

**Issue by cfhull** [Hyperobjekt/seeing-solitary#135]

**Comment by cfhull** [comment]
@james-minton Let me know if this styling doesn't work for you.

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/5115526/198754925-d905cb5b-dba5-45e1-a189-3cef84fc4d82.png">

**Comment by james-minton** [comment]
Works for me @cfhull !
