### ISSUE TITLE
Mobile versions of State/Federal and Jurisdiction pages

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#147]
## Mobile version

- [ ] mobile version of these pages should be implemented per mockups
  - [ ] horizontal bar charts will need to become vertical on phones, per mockups

**Comment by james-minton** [comment]
@cfhull some further changes to charts for mobile --

Sometimes X axis labels collide. Can we put them on a slant/45 degree angle on mobile?

<img width="366" alt="Screen Shot 2022-11-06 at 6 20 38 PM" src="https://user-images.githubusercontent.com/33635008/200203709-852c2d82-3567-44ad-8886-fe3f025d1264.png">

**Comment by james-minton** [comment]
Closing this one and moving issue in comment above to #181
