### ISSUE TITLE
Table section mobile

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#148]
- [x] On mobile/tablet, where it makes sense, table should be horizontally scrollable instead of trying to fit all columns into a small viewport

**Comment by aarondentrodev** [comment]
@lizlove The only page using table is state and federal overview page and it is already fixed by @cfhull .

![image](https://user-images.githubusercontent.com/57238602/199174766-676ef908-9b2a-494a-93f1-1f532d0eb2a2.png)
