### ISSUE TITLE
Trans data update values

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#150]
- [ ] **Trans data they provided earlier has some missing years**. Those years have been sent over to us in [this sheet ](https://docs.google.com/spreadsheets/d/1Ie3csrOwHiWuPVQvFsR9lAhU34dr1Rfu/edit?usp=sharing&ouid=100970010941426875871&rtpof=true&sd=true)and need to be added to the charts.

**Comment by james-minton** [comment]
Just marking that data provided for earlier years is missing @lizlove :

<img width="825" alt="Screen Shot 2022-10-31 at 10 58 08 AM" src="https://user-images.githubusercontent.com/33635008/199039057-4770cb09-ef63-435b-b036-cc354e52bc30.png">
