### ISSUE TITLE
Where values are zero in bar charts, should have "0%" or "0" in place of the bar (as shown in mockups)- see issue

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#152]

**Comment by james-minton** [comment]
@cfhull / @lizlove this looks great where applied -- seems like it is on state-and-federal but not other jurisdictions? E.g. California

<img width="1286" alt="Screen Shot 2022-10-31 at 10 40 43 AM" src="https://user-images.githubusercontent.com/33635008/199035077-7560a8c0-351b-4268-9bf7-601a0565b566.png">

**Comment by cfhull** [comment]
I probably just need to add it to another bar chart component that I missed. I'll fix that asap.
