### ISSUE TITLE
 Fix appearance of zero values for for charts where all values are zero 

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#153]
Fix appearance of zero values for for charts where all values are zero (e.g. pregnant people in solitary on state/federal). The zero line is elevated in the Y axis but should be at the bottom of the chart, and should show "0" in place of the bar for all values per note above

**Comment by cfhull** [comment]
Does this cover the requirements? I set the min scale to 5, so we'll always see `1, 2, 3, 4, 5` unless any of the values are higher, in which case it will scale with the max value.
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/5115526/198908331-92d4bcbc-7896-4403-9d0c-1bb5e1476fb7.png">

**Comment by lizlove** [comment]
@james-minton does this work for you?
