### ISSUE TITLE
Left align label text on rules bars

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#162]
- Wrap text also if possible. 
- 
<img width="530" alt="Screen Shot 2022-10-30 at 10 40 00 PM" src="https://user-images.githubusercontent.com/7707627/198926582-0fd4e9b0-31ac-4e2e-a4b2-8d1afe3541f0.png">

**Comment by cfhull** [comment]
@james-minton Did I interpret this correctly? 
![image](https://user-images.githubusercontent.com/5115526/207943018-a40b611a-5a6e-44c8-a646-6006fef422a7.png)

**Comment by james-minton** [comment]
Yes thanks!
