### ISSUE TITLE
Data issues to be fixed before launch

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seeing-solitary#179]
- [x] Individual jurisdictions: “What were the ages of people in solitary?” charts are showing the same values across all jurisdictions (e.g. Arizona’s page has the same data for Age as Alabama)
- [x] State and Federal: “How many people?” — the denominator for 2019/men’s prisons is coming from `2019_smi_total_custodial_male` when it should be coming from `2019_total_custodial_male`
- [x] State and Federal: “Transgender, 2017” — percentages (or numerator/denominator) are wrong. 
- [x] State and Federal + jurisdictions: “Race & Ethnicity” — cut "total custodial population" entirely
- [x] State and Federal: “How many people?” — the tooltip for 2021/women’s prisons is not picking up `cust` and `rh` values, so the tooltip doesn’t show values (though the bar chart is correct)
- [x] State and Federal + Jurisdiction: "Overview" section — large numbers are being reported without commas, e.g. "25083." Please format these with commas.
- [x] Racial/ethnic section on individual jurisdictions still showing this issue when all values are zero
<img width="1316" alt="Screen Shot 2022-11-06 at 6 21 29 PM" src="https://user-images.githubusercontent.com/33635008/200203789-6741aea2-7d84-46ad-a931-26fac1441880.png">

**Comment by cfhull** [comment]
How come this was closed?

**Comment by james-minton** [comment]
Looks like an oopsie. Reopening.

**Comment by cfhull** [comment]
It looks like there is only transgender data for 2021. Whatever was showing on the site must have been a bug. I fixed it so it's using the correct data from the CSV.

**Comment by cfhull** [comment]
I don't fully understand `State and Federal + jurisdictions: “Race & Ethnicity” — cut "total custodial population" entirely` Are you just wanting to remove the gray bar, or do you want it from the tooltip as well?

**Comment by james-minton** [comment]
@cfhull my mistake - d'oh! Keep the grey bar and the tooltip heading, just need to add in the data point for "total custodial" to the tooltips

**Comment by cfhull** [comment]
The tooltips don't really make sense though, do they? If I hover over `White` - `Total custodial (blue bar)` What are we supposed to show for `in solitary` for the tooltip? It seems to me like there should be a different tooltip for blue vs gray.

Currently, we have in solitary / total custodial, but I think it should be this (with better phrasing)?
- Blue: \<race\> in total custodial / total custodial
- Gray: \<race\> in solitary and total in solitary

What do you think?

**Comment by cfhull** [comment]
@james-minton done and ready to test
