### ISSUE TITLE
Homepage animations 

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seeing-solitary#185]
- [ ] Currently only the tally marks in full black are animated. Can _all_ of them animate from left to right? Probably best would be the top row first, then the second row. I know some of them extend beyond the right edge of the viewport, though, which could complicate things; I don't have a problem cutting the ones to the right off at some sensible point so that there isn't a huge delay in animating the second row (or the second row could start a bit before the first one ends?).

![Screen Shot 2022-12-13 at 12 42 35 PM](https://user-images.githubusercontent.com/33635008/207407094-73b5a98a-40b7-463e-b767-89ce2c674286.png)

**Comment by james-minton** [comment]
@cfhull updated this (formerly "stub") ticket with a request ☝️

**Comment by cfhull** [comment]
Think I have something that looks good. Demo is available at the linked PR.
