### ISSUE TITLE
Individual states charts QA

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seeing-solitary#195]
Would be good to do a run-through of individual state pages charts—seeing issues at random, -- e.g. Delaware

<img width="1318" alt="Screen Shot 2022-12-19 at 10 03 59 AM" src="https://user-images.githubusercontent.com/33635008/208457269-ef4c92cd-d373-49a2-9f9d-aa2cd9c18f07.png">
<img width="1328" alt="Screen Shot 2022-12-19 at 10 04 18 AM" src="https://user-images.githubusercontent.com/33635008/208457299-e7bcf712-44f2-45e3-bf73-1d1dce457e81.png">

Indiana, empty chart:

<img width="1292" alt="Screen Shot 2022-12-19 at 10 04 37 AM" src="https://user-images.githubusercontent.com/33635008/208457314-b060647a-cbe5-4056-9115-2cc53d7e2f53.png">

The above were found clicking around at random, would be good to comb through systematically.

**Comment by cfhull** [comment]
@james-minton I went through all of the jurisdictions today and corrected the issues I found, which included those above. Most of it was inconsistencies with `null`, `0`, 'undefined', 'nodata', etc, and how we show those values.
