### ISSUE TITLE
Develop "Ancillary pages" for all breakpoints

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/seeing-solitary#36]
"Ancillary pages" are pages besides the homepage and other data visualization-focused pages (e.g. state and federal overview, individual jurisdiction pages). So far these are

- About
- Reports
- Resources
- Methods
- Glossary & FAQ

Please refer to [this mockup](https://www.figma.com/file/JrvMTSccXdO97taW5dWK62/Yale-Seeing-Solitary-HP?node-id=968%3A7488) for the FAQ page and other ancillary pages.

## General specs for these pages

- [ ] We do not have designs for breakpoints besides desktop, but I am hoping that other breakpoint designs in the PRODUCTION page in Figma can serve as a guide, along with the [style guide](https://www.figma.com/file/JrvMTSccXdO97taW5dWK62/Yale-Seeing-Solitary-HP?node-id=863%3A7084).
- [ ] Pages are currently lacking a hero component. This should be a single reusable component for this and other "ancillary" pages like Reports, About, etc., since they all use the same layout. (Please do not create hero components for each of these pages individually.)
- [ ] Ensure that type is encoded using semantic tags (h1, h2, p, etc.). This is necessary for accessibility and other reasons. Styles for these tags can be configured in `tailwindsconfig.js` -- do not encode text styles inline, save for exceptional cases.
- [ ] Ideally: content should be separated from layout, so that it is not hardcoded and a non-coder can manage content. MDX or other markdown-style contents files are preferred, so they can be integrated with a CMS at some point, such as [Netlify CMS.](https://www.netlifycms.org/) See [issue](https://github.com/Hyperobjekt/seeing-solitary/issues/37).
- [ ] Pages should have a "jump to section" floating menu component. See [Reports page mockup](https://www.figma.com/file/JrvMTSccXdO97taW5dWK62/Yale-Seeing-Solitary-HP?node-id=968%3A7488) for example of when the menu is closed, and [here for what the menu should look like when open](https://www.figma.com/file/JrvMTSccXdO97taW5dWK62/Yale-Seeing-Solitary-HP?node-id=894%3A9179). 
  - [ ] This menu should use "sticky" positioning to float with the page
  - [ ] Clicking on any link should smooth-scroll the user to the link—it should not be an instantaneous jump.
  - [ ] Major sections should have unique id's to facilitate these links. 

## Specs for individual pages

- [ ] **The FAQ/Glossary page** currently uses accordions to manage long content, but we need to remove these, as the client's content is too long to fit in accordions. Instead, we are going to expose all content on the page and use the floating menu described above to jump to different sections.

**Comment by cfhull** [comment]
There may be some follow-up to this, but we can call this one done.
