### ISSUE TITLE
Add monospace font family

### ISSUE THREAD

**Issue by cfhull** [Hyperobjekt/seeing-solitary#69]
Figma is using "Nitti" as a monospace font. We either need to get the license to use it or choose a free alternative.

Additionally, we need to set various components to use `font-mono`.

**Comment by james-minton** [comment]
@cfhull thanks for reminding me of this. Should be ready to go:

>To use these fonts on a web page, copy this code into the <head> tag of your HTML.
You can embed this project on any website you manage.

`<link rel="stylesheet" href="https://use.typekit.net/xcx6irr.css">`

(Not sure if maybe Next.js has a different way of integrating webfonts like Gatsby does, or if the above will work.)
---

Project ID: xcx6irr

font-family: nitti, monospace;
font-style: normal;

Weights:

Regular= font-weight: 400, Medium=500, bold=700

**Comment by cfhull** [comment]
This looks so much better now! I also added the `font-mono` class to all the components that needed it, based on the mockups.
