### ISSUE TITLE
Template for individual state pages

### ISSUE THREAD

**Issue by lizlove** [Hyperobjekt/seeing-solitary#7]
- [x] Create individual state template that is rendered  at `/states/<state/.`
- [x] Inherit the state name from the route? 
- [x] Create a hook to show the appropriate map coordinates from `src/common/data/us_state_centers.json`

**Comment by james-minton** [comment]
Reminder @lizlove that we are updating `/states/[state]` to `/jurisdictions/[jurisdiction]`

E.g. 

- `/jurisdictions/alabama`
- `/jurisdictions/bureau-of-prisons`

**Comment by lizlove** [comment]
Moved the above comment to a separate ticket, #49 
@james-minton
