### ISSUE TITLE
Clicking navigation item should close navigation dropdown

### ISSUE THREAD

**Issue by cfhull** [Hyperobjekt/seeing-solitary#71]
https://hyperobjekt.slack.com/archives/C044RJBJV1A/p1665857601488869?thread_ts=1665855955.531789&cid=C044RJBJV1A

**Comment by aarondentrodev** [comment]
@dextermichael I think you are better than me to solve this issue.

**Comment by dextermichael** [comment]
> @dextermichael I think you are better than me to solve this issue.

@aarondentrodev ok, I will take a look at this.

**Comment by james-minton** [comment]
@dextermichael can you update on the status of this?

**Comment by dextermichael** [comment]
> @dextermichael can you update on the status of this?

This has been a bit challenging because it needs restructuring the existing Header component, but I am trying to fix this without huge refactoring. I will try more tonight.

**Comment by james-minton** [comment]
Ok thank you @dextermichael! In case this is something that's also implicated in your fixes, here's another issue I just created for the nav: https://github.com/Hyperobjekt/seeing-solitary/issues/159
